name: Publish Extension

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test

      - name: Build and package extension
        run: pnpm package

      - name: Publish to Visual Studio Marketplace
        env:
          VSCODE_PAT: ${{ secrets.VSCODE_PAT }}
        run: pnpm publish:vsce -p "$VSCODE_PAT"

      - name: Publish to Open VSX
        env:
          VSX_PAT: ${{ secrets.VSX_PAT }}
        run: pnpm publish:ovsx -p "$VSX_PAT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
